# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\北信实习\纸板计数\my_counter\myUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 1400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_detect = QtWidgets.QPushButton(self.centralwidget)
        self.Button_detect.setGeometry(QtCore.QRect(820, 310, 81, 31))
        self.Button_detect.setObjectName("Button_detect")
        self.Button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.Button_exit.setGeometry(QtCore.QRect(820, 430, 81, 31))
        self.Button_exit.setObjectName("Button_exit")
        self.arg_Slider = QtWidgets.QSlider(self.centralwidget)
        self.arg_Slider.setGeometry(QtCore.QRect(800, 500, 131, 20))
        self.arg_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.arg_Slider.setObjectName("arg_Slider")
        self.toolButton_imgcut = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_imgcut.setGeometry(QtCore.QRect(820, 250, 81, 31))
        self.toolButton_imgcut.setObjectName("toolButton_imgcut")
        self.Button_save = QtWidgets.QPushButton(self.centralwidget)
        self.Button_save.setGeometry(QtCore.QRect(820, 370, 81, 31))
        self.Button_save.setObjectName("Button_save")
        self.lcdNumber_result = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_result.setGeometry(QtCore.QRect(820, 60, 81, 31))
        self.lcdNumber_result.setObjectName("lcdNumber_result")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(820, 40, 71, 21))
        self.label_result.setObjectName("label_result")
        self.Button_imginput = QtWidgets.QPushButton(self.centralwidget)
        self.Button_imginput.setGeometry(QtCore.QRect(820, 190, 81, 31))
        self.Button_imginput.setObjectName("Button_imginput")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(820, 130, 81, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_show = QtWidgets.QLabel(self.centralwidget)
        self.label_show.setGeometry(QtCore.QRect(40, 40, 720, 1280))
        self.label_show.setObjectName("label_show")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 40, 720, 1280))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 718, 1278))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_show.raise_()
        self.Button_detect.raise_()
        self.Button_exit.raise_()
        self.arg_Slider.raise_()
        self.toolButton_imgcut.raise_()
        self.Button_save.raise_()
        self.lcdNumber_result.raise_()
        self.label_result.raise_()
        self.Button_imginput.raise_()
        self.pushButton_5.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_detect.setText(_translate("MainWindow", "检测"))
        self.Button_exit.setText(_translate("MainWindow", "退出"))
        self.toolButton_imgcut.setText(_translate("MainWindow", "检测区域"))
        self.Button_save.setText(_translate("MainWindow", "保存"))
        self.label_result.setText(_translate("MainWindow", "总数"))
        self.Button_imginput.setText(_translate("MainWindow", "图片导入"))
        self.pushButton_5.setText(_translate("MainWindow", "拍照"))
        self.label_show.setText(_translate("MainWindow", "TextLabel"))
